### ISSUE TITLE
Error when running npm install 

### ISSUE THREAD

**Issue by Rexdomine** [kylelobo/AuthentiFi#7]
hi there nice work so far but I keep getting errors when I try to run npm install as seen below please how can I get passed this issue thank you.

npm WARN old lockfile 
npm WARN old lockfile The package-lock.json file was created with an old version of npm,
npm WARN old lockfile so supplemental metadata must be fetched from the registry.
npm WARN old lockfile 
npm WARN old lockfile This is a one-time fix-up, please be patient...
npm WARN old lockfile 
npm WARN deprecated bcrypt@3.0.3: versions < v5.0.0 do not handle NUL in passwords properly
npm WARN deprecated crypto@1.0.1: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code 1
npm ERR! path /Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt
npm ERR! command failed
npm ERR! command sh -c node-pre-gyp install --fallback-to-build
npm ERR! CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
npm ERR!   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
npm ERR!   CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
npm ERR! Failed to execute '/usr/local/Cellar/node/18.0.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp info it worked if it ends with ok
npm ERR! node-pre-gyp info using node-pre-gyp@0.12.0
npm ERR! node-pre-gyp info using node@18.0.0 | darwin | x64
npm ERR! node-pre-gyp WARN Using needle for node-pre-gyp https download 
npm ERR! node-pre-gyp info check checked for "/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding/bcrypt_lib.node" (not found)
npm ERR! node-pre-gyp http GET https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.3/bcrypt_lib-v3.0.3-node-v108-darwin-x64-unknown.tar.gz
npm ERR! node-pre-gyp http 404 https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.3/bcrypt_lib-v3.0.3-node-v108-darwin-x64-unknown.tar.gz
npm ERR! node-pre-gyp WARN Tried to download(404): https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.3/bcrypt_lib-v3.0.3-node-v108-darwin-x64-unknown.tar.gz 
npm ERR! node-pre-gyp WARN Pre-built binaries not found for bcrypt@3.0.3 and node@18.0.0 (node-v108 ABI, unknown) (falling back to source compile with node-gyp) 
npm ERR! node-pre-gyp http 404 status code downloading tarball https://github.com/kelektiv/node.bcrypt.js/releases/download/v3.0.3/bcrypt_lib-v3.0.3-node-v108-darwin-x64-unknown.tar.gz 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.0.0 | darwin | x64
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.0.0 | darwin | x64
npm ERR! gyp info find Python using Python version 3.8.9 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/Rexdomine/Library/Caches/node-gyp/18.0.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/Rexdomine/Library/Caches/node-gyp/18.0.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info ok 
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.0.0
npm ERR! gyp info using node@18.0.0 | darwin | x64
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:222:
npm ERR! In file included from ../../nan/nan_converters.h:67:
npm ERR! ../../nan/nan_converters_43_inl.h:22:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
npm ERR! X(Boolean)
npm ERR! ^~~~~~~~~~
npm ERR! ../../nan/nan_converters_43_inl.h:18:23: note: expanded from macro 'X'
npm ERR!       val->To ## TYPE(isolate->GetCurrentContext())                            \
npm ERR!                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:398:37: note: passing argument to parameter 'isolate' here
npm ERR!   Local<Boolean> ToBoolean(Isolate* isolate) const;
npm ERR!                                     ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:222:
npm ERR! In file included from ../../nan/nan_converters.h:67:
npm ERR! ../../nan/nan_converters_43_inl.h:22:1: error: no member named 'FromMaybe' in 'v8::Local<v8::Boolean>'
npm ERR! X(Boolean)
npm ERR! ^~~~~~~~~~
npm ERR! ../../nan/nan_converters_43_inl.h:19:12: note: expanded from macro 'X'
npm ERR!           .FromMaybe(v8::Local<v8::TYPE>()));                                  \
npm ERR!            ^
npm ERR! ../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from 'Local<v8::Context>' to 'v8::Isolate *'
npm ERR! X(bool, Boolean)
npm ERR! ^~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan_converters_43_inl.h:37:29: note: expanded from macro 'X'
npm ERR!   return val->NAME ## Value(isolate->GetCurrentContext());                     \
npm ERR!                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:408:30: note: passing argument to parameter 'isolate' here
npm ERR!   bool BooleanValue(Isolate* isolate) const;
npm ERR!                              ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:222:
npm ERR! In file included from ../../nan/nan_converters.h:67:
npm ERR! ../../nan/nan_converters_43_inl.h:40:1: error: no viable conversion from returned value of type 'bool' to function return type 'imp::ToFactory<bool>::return_t' (aka 'Maybe<bool>')
npm ERR! X(bool, Boolean)
npm ERR! ^~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan_converters_43_inl.h:37:10: note: expanded from macro 'X'
npm ERR!   return val->NAME ## Value(isolate->GetCurrentContext());                     \
npm ERR!          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-maybe.h:29:7: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from 'bool' to 'const v8::Maybe<bool> &' for 1st argument
npm ERR! class Maybe {
npm ERR!       ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-maybe.h:29:7: note: candidate constructor (the implicit move constructor) not viable: no known conversion from 'bool' to 'v8::Maybe<bool> &&' for 1st argument
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-maybe.h:84:12: note: explicit constructor is not a candidate
npm ERR!   explicit Maybe(const T& t) : has_value_(true), value_(t) {}
npm ERR!            ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:223:
npm ERR! In file included from ../../nan/nan_new.h:189:
npm ERR! ../../nan/nan_implementation_12_inl.h:356:37: error: too few arguments to function call, expected 2, have 1
npm ERR!   return v8::StringObject::New(value).As<v8::StringObject>();
npm ERR!          ~~~~~~~~~~~~~~~~~~~~~      ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-primitive-object.h:81:23: note: 'New' declared here
npm ERR!   static Local<Value> New(Isolate* isolate, Local<String> value);
npm ERR!                       ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! ../../nan/nan.h:2470:8: warning: 'SetAccessor' is deprecated: Do signature check in accessor [-Wdeprecated-declarations]
npm ERR!   tpl->SetAccessor(
npm ERR!        ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-template.h:837:3: note: 'SetAccessor' has been explicitly marked deprecated here
npm ERR!   V8_DEPRECATED("Do signature check in accessor")
npm ERR!   ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8config.h:460:35: note: expanded from macro 'V8_DEPRECATED'
npm ERR! # define V8_DEPRECATED(message) [[deprecated(message)]]
npm ERR!                                   ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:2722:
npm ERR! ../../nan/nan_object_wrap.h:24:25: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object>'
npm ERR!     assert(persistent().IsNearDeath());
npm ERR!            ~~~~~~~~~~~~ ^
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
npm ERR!     (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
npm ERR!                         ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:2722:
npm ERR! ../../nan/nan_object_wrap.h:127:26: error: no member named 'IsNearDeath' in 'Nan::Persistent<v8::Object>'
npm ERR!     assert(wrap->handle_.IsNearDeath());
npm ERR!            ~~~~~~~~~~~~~ ^
npm ERR! /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/assert.h:99:25: note: expanded from macro 'assert'
npm ERR!     (__builtin_expect(!(e), 0) ? __assert_rtn(__func__, __ASSERT_FILE_NAME, __LINE__, #e) : (void)0)
npm ERR!                         ^
npm ERR! In file included from ../src/bcrypt_node.cc:1:
npm ERR! In file included from ../../nan/nan.h:2818:
npm ERR! ../../nan/nan_typedarray_contents.h:34:43: error: no member named 'GetContents' in 'v8::ArrayBuffer'
npm ERR!       data   = static_cast<char*>(buffer->GetContents().Data()) + byte_offset;
npm ERR!                                   ~~~~~~~~^
npm ERR! ../src/bcrypt_node.cc:66:21: error: no matching constructor for initialization of 'String::Utf8Value'
npm ERR!   String::Utf8Value value(str);
npm ERR!                     ^     ~~~
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-primitive.h:517:5: note: candidate constructor not viable: no known conversion from 'Local<v8::String>' to 'const v8::String::Utf8Value' for 1st argument
npm ERR!     Utf8Value(const Utf8Value&) = delete;
npm ERR!     ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-primitive.h:510:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
npm ERR!     Utf8Value(Isolate* isolate, Local<v8::Value> obj);
npm ERR!     ^
npm ERR! ../src/bcrypt_node.cc:121:60: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     const char minor_ver = ToCharVersion(info[0]->ToString());
npm ERR!                                          ~~~~~~~~~~~~~~~~~ ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:360:44: note: 'ToString' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
npm ERR!                                            ^
npm ERR! ../src/bcrypt_node.cc:121:28: error: no matching function for call to 'ToCharVersion'
npm ERR!     const char minor_ver = ToCharVersion(info[0]->ToString());
npm ERR!                            ^~~~~~~~~~~~~
npm ERR! ../src/bcrypt_node.cc:65:6: note: candidate function not viable: no known conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>' for 1st argument
npm ERR! char ToCharVersion(Local<String> str) {
npm ERR!      ^
npm ERR! ../src/bcrypt_node.cc:150:60: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     const char minor_ver = ToCharVersion(info[0]->ToString());
npm ERR!                                          ~~~~~~~~~~~~~~~~~ ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:360:44: note: 'ToString' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
npm ERR!                                            ^
npm ERR! ../src/bcrypt_node.cc:150:28: error: no matching function for call to 'ToCharVersion'
npm ERR!     const char minor_ver = ToCharVersion(info[0]->ToString());
npm ERR!                            ^~~~~~~~~~~~~
npm ERR! ../src/bcrypt_node.cc:65:6: note: candidate function not viable: no known conversion from 'MaybeLocal<v8::String>' to 'Local<v8::String>' for 1st argument
npm ERR! char ToCharVersion(Local<String> str) {
npm ERR!      ^
npm ERR! ../src/bcrypt_node.cc:212:44: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     Nan::Utf8String data(info[0]->ToString());
npm ERR!                          ~~~~~~~~~~~~~~~~~ ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:360:44: note: 'ToString' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
npm ERR!                                            ^
npm ERR! ../src/bcrypt_node.cc:212:21: error: no matching constructor for initialization of 'Nan::Utf8String'
npm ERR!     Nan::Utf8String data(info[0]->ToString());
npm ERR!                     ^    ~~~~~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan.h:1060:19: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::Value>' for 1st argument
npm ERR!   inline explicit Utf8String(v8::Local<v8::Value> from) :
npm ERR!                   ^
npm ERR! ../../nan/nan.h:1120:33: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'const Nan::Utf8String' for 1st argument
npm ERR!   NAN_DISALLOW_ASSIGN_COPY_MOVE(Utf8String)
npm ERR!                                 ^
npm ERR! ../../nan/nan.h:137:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
npm ERR!     NAN_DISALLOW_COPY(CLASS)                                                   \
npm ERR!                       ^
npm ERR! ../../nan/nan.h:113:35: note: expanded from macro 'NAN_DISALLOW_COPY'
npm ERR! # define NAN_DISALLOW_COPY(CLASS) CLASS(const CLASS&) = delete;
npm ERR!                                   ^
npm ERR! ../../nan/nan.h:1120:33: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'Nan::Utf8String' for 1st argument
npm ERR! ../../nan/nan.h:138:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
npm ERR!     NAN_DISALLOW_MOVE(CLASS)
npm ERR!                       ^
npm ERR! ../../nan/nan.h:115:5: note: expanded from macro 'NAN_DISALLOW_MOVE'
npm ERR!     CLASS(CLASS&&) = delete;  /* NOLINT(build/c++11) */                        \
npm ERR!     ^
npm ERR! ../src/bcrypt_node.cc:213:44: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     Nan::Utf8String salt(info[1]->ToString());
npm ERR!                          ~~~~~~~~~~~~~~~~~ ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:360:44: note: 'ToString' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
npm ERR!                                            ^
npm ERR! ../src/bcrypt_node.cc:213:21: error: no matching constructor for initialization of 'Nan::Utf8String'
npm ERR!     Nan::Utf8String salt(info[1]->ToString());
npm ERR!                     ^    ~~~~~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan.h:1060:19: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::Value>' for 1st argument
npm ERR!   inline explicit Utf8String(v8::Local<v8::Value> from) :
npm ERR!                   ^
npm ERR! ../../nan/nan.h:1120:33: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'const Nan::Utf8String' for 1st argument
npm ERR!   NAN_DISALLOW_ASSIGN_COPY_MOVE(Utf8String)
npm ERR!                                 ^
npm ERR! ../../nan/nan.h:137:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
npm ERR!     NAN_DISALLOW_COPY(CLASS)                                                   \
npm ERR!                       ^
npm ERR! ../../nan/nan.h:113:35: note: expanded from macro 'NAN_DISALLOW_COPY'
npm ERR! # define NAN_DISALLOW_COPY(CLASS) CLASS(const CLASS&) = delete;
npm ERR!                                   ^
npm ERR! ../../nan/nan.h:1120:33: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'Nan::Utf8String' for 1st argument
npm ERR! ../../nan/nan.h:138:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
npm ERR!     NAN_DISALLOW_MOVE(CLASS)
npm ERR!                       ^
npm ERR! ../../nan/nan.h:115:5: note: expanded from macro 'NAN_DISALLOW_MOVE'
npm ERR!     CLASS(CLASS&&) = delete;  /* NOLINT(build/c++11) */                        \
npm ERR!     ^
npm ERR! ../src/bcrypt_node.cc:231:44: error: too few arguments to function call, single argument 'context' was not specified
npm ERR!     Nan::Utf8String data(info[0]->ToString());
npm ERR!                          ~~~~~~~~~~~~~~~~~ ^
npm ERR! /Users/Rexdomine/Library/Caches/node-gyp/18.0.0/include/node/v8-value.h:360:44: note: 'ToString' declared here
npm ERR!   V8_WARN_UNUSED_RESULT MaybeLocal<String> ToString(
npm ERR!                                            ^
npm ERR! ../src/bcrypt_node.cc:231:21: error: no matching constructor for initialization of 'Nan::Utf8String'
npm ERR!     Nan::Utf8String data(info[0]->ToString());
npm ERR!                     ^    ~~~~~~~~~~~~~~~~~~~
npm ERR! ../../nan/nan.h:1060:19: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'v8::Local<v8::Value>' for 1st argument
npm ERR!   inline explicit Utf8String(v8::Local<v8::Value> from) :
npm ERR!                   ^
npm ERR! ../../nan/nan.h:1120:33: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'const Nan::Utf8String' for 1st argument
npm ERR!   NAN_DISALLOW_ASSIGN_COPY_MOVE(Utf8String)
npm ERR!                                 ^
npm ERR! ../../nan/nan.h:137:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
npm ERR!     NAN_DISALLOW_COPY(CLASS)                                                   \
npm ERR!                       ^
npm ERR! ../../nan/nan.h:113:35: note: expanded from macro 'NAN_DISALLOW_COPY'
npm ERR! # define NAN_DISALLOW_COPY(CLASS) CLASS(const CLASS&) = delete;
npm ERR!                                   ^
npm ERR! ../../nan/nan.h:1120:33: note: candidate constructor not viable: no known conversion from 'MaybeLocal<v8::String>' to 'Nan::Utf8String' for 1st argument
npm ERR! ../../nan/nan.h:138:23: note: expanded from macro 'NAN_DISALLOW_ASSIGN_COPY_MOVE'
npm ERR!     NAN_DISALLOW_MOVE(CLASS)
npm ERR!                       ^
npm ERR! ../../nan/nan.h:115:5: note: expanded from macro 'NAN_DISALLOW_MOVE'
npm ERR!     CLASS(CLASS&&) = delete;  /* NOLINT(build/c++11) */                        \
npm ERR!     ^
npm ERR! fatal error: too many errors emitted, stopping now [-ferror-limit=]
npm ERR! 1 warning and 20 errors generated.
npm ERR! make: *** [Release/obj.target/bcrypt_lib/src/bcrypt_node.o] Error 1
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:291:12)
npm ERR! gyp ERR! System Darwin 21.2.0
npm ERR! gyp ERR! command "/usr/local/Cellar/node/18.0.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding/bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v108"
npm ERR! gyp ERR! cwd /Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt
npm ERR! gyp ERR! node -v v18.0.0
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/Cellar/node/18.0.0/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding/bcrypt_lib.node --module_name=bcrypt_lib --module_path=/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v108' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:527:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1090:16)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Darwin 21.2.0
npm ERR! node-pre-gyp ERR! command "/usr/local/Cellar/node/18.0.0/bin/node" "/Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /Volumes/Untitled/Conterfix/AuthentiFi/node_modules/bcrypt
npm ERR! node-pre-gyp ERR! node -v v18.0.0
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v0.12.0
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/Rexdomine/.npm/_logs/2022-05-16T14_44_45_679Z-debug-0.log

**Comment by 1k0n1ck** [comment]
Getting the same error. How did you correct this?
